import { type NextPage } from "next";
import Head from "next/head";
import Banner from "~/components/Home/Banner";
import Navbar from "~/components/layout/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Safe Haven</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="min-h-screen w-full bg-primary">
        <Banner />
      </div>
    </>
  );
};

export default Home;
